### ISSUE TITLE
refactor: parse_date@64-159@jarviscli/utilities/textParser.py

### ISSUE THREAD

**Issue by joberg92** [remnestal/Jarvis#14]
Respond to this issue with a description of how you think the *parse_date* function could be refactored to decrease its CCN. The goal is to lower CCN by at least 35%.

**Or even better**, if you think that there is some simple refactor that you can make now; then do it and make a pull request to [branch/refactor-decrease-complexity](https://github.com/remnestal/Jarvis/tree/refactor-decrease-complexity)

**Comment by remnestal** [comment]
This refacoring reduced the complexity from 27 to 15 (according to lizard). The three resulting additional functions has a CCN value of 5, 5, 8. The changes were added by #22
