### ISSUE TITLE
chore: Count CCN for main@8-77@./packages/weather_pinpoint.py

### ISSUE THREAD

**Issue by marcus-wengelin** [remnestal/Jarvis#6]
Count cyclomatic complexity (CCN) for main function by hand. See https://en.wikipedia.org/wiki/Cyclomatic_complexity

**Comment by remnestal** [comment]
This issue seems to have been added by mistake, we're not required to count the CNN for _main@8-77@./packages/weather_pinpoint.py_ manually.
